const blackDark = "#191B20";
const darkDarker = "#1F2128";
const darkLighter = "#242731";
const gray = "#E4E4E4";

export default {
  rewards: {
    backgroundColor: "#1F2128",
    "& h2": {
      position: "absolute",
      width: "168px",
      height: "40px",
      left: "40px",
      top: "160px",
      fontFamily: "Aeonik",
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: "26px",
      lineHeight: "40px",
      color: "#FFFFFF",
    },
  },
  rewardsContainer: {
    position: "absolute",
    width: "448px",
    height: "840px",
    left: "40px",
    top: "208px",
    background: "#242731",
    backdropFilter: "blur(16px)",
    borderRadius: "24px",
  },
  cryptoOptions: {
    position: "absolute",
    left: "5.94%",
    right: "92.71%",
    top: "48.15%",
    bottom: "50%",
    fontFamily: "Aeonik",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "14px",
    lineHeight: "20px",
    color: "#FFFFFF",
    "& li": {
      position: "absolute",
      width: "1px",
      height: "24px",
      left: "188px",
      top: "518px",
      background: "#FFFFFF",
      opacity: "0.1",
    },
  },
  circleItem: {
    "& svg": {
      position: "absolute",
    },
  },
  circlesSection: {
    height: "256px",
    width: "100%",
    "& svg": {
      height: "initial !important",
      width: "initial !important",
    },
    "& circle": {
      display: "none !important",
    },
  },
  removeIcon: {
    top: "25px",
    position: "absolute",
    background: "#1C1F29",
    width: "48px",
    height: "48px",
    right: "25px",
    display: "flex",
    justifyContent: "center",
    alignContent: "center",
    borderRadius: "100%",
    alignItems: "center",
  },
  cryptoListItem: {
    position: "relative",
    width: "400px !important",
    height: "60px !important",
    "& > div": {
      background: "#242731",
    },
    overflow: "hidden",
    borderRadius: "12px",
    "& span": {
      fontFamily: "Aeonik",
      fontStyle: "normal",
      fontWeight: "normal",
      fontSize: "14px",
      lineHeight: "24px",
      textAlign: "right",
      color: "#FFFFFF",
    },
    "& h4": {
      fontFamily: "Aeonik",
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: "18px",
      lineHeight: "24px",
      color: "#FFFFFF",
      flex: "none",
      order: "0",
      flexGrow: "0",
      margin: "0px 4px",
    },
    "& .MuiSlider-colorPrimary": {
      color: "#1D87E8 !important",
      width: "196px",
      height: "16px",
    },
    "& .MuiSlider-thumb.Mui-active": {
      boxShadow: "initial !important",
    },
    "& .MuiSlider-thumb.Mui-focusVisible, .MuiSlider-thumb:hover": {
      boxShadow: " none !important",
    },
    "& .MuiSlider-rail": {
      backgroundColor: "#F4F4F4 !important",

      height: "2px !important",
    },
    "& .MuiSlider-track": {
      height: "2px !important",
    },
    "& .MuiSlider-thumbColorPrimary": {
      background: "#1C1F29",
      border: "2px solid #FFFFFF",
      boxSizing: "border-box",
      width: "16px",
      height: "16px",
    },
  },
  dropDown: {
    position: "absolute",
    width: "148px",
    height: "56px",
    left: "340px",
    top: "136px",
    background: "#191B20",
    borderRadius: "12px",
    "& span": {
      position: "absolute",
      width: "52px",
      height: "24px",
      left: "356px",
      top: "152px",
      fontFamily: "Aeonik",
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: "14px",
      lineHeight: "24px",
      color: "#FFFFFF",
    },
  },
  multiList: {
    background: "#242731 !important",
  },
  addNewItem: {
    border: "1px solid rgba(228, 228, 228, 0.1)",
    boxSizing: "border-box",
    borderRadius: "12px",
    width: "400px",
    height: "60px",
    display: "block",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    "& span": {
      fontFamily: "Aeonik",
      fontStyle: "normal",
      fontWeight: "normal",
      fontSize: "14px",
      lineHeight: "24px",
      color: "#808191",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    },
  },
  plusIcon: {
    width: "44px",
    height: "44px",
    background: "rgba(228,228,228, 0.1)",
    borderRadius: "12px",
    position: "absolute",
    left: "8px",
    top: "calc(30px - 22px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "& img": {
      height: "20px",
      width: "20px",
      borderRadius: "0px",
    },
  },
  selectorContainer: {
    position: "relative",
    display: "flex",
    flexWrap: "wrap",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  sliderIcon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "& img": {
      width: "28px",
      height: "28px",
    },
    "& .img-name": {
      fontFamily: "Aeonik",
      fontStyle: "normal",
      fontWeight: "bold",
      fontSize: "18px",
      lineHeight: "24px",
      color: "#FFFFFF",
    },
    "& .img-chevron": {
      width: "16px",
      height: "16px",
      flex: "none",
      order: "1",
      flexGrow: "0",
      margin: "0px 4px",
    },
  },
  trackWrapper: {
    backgroundColor: "#1C1F29",
    height: "100% !important",
    width: "292px !important",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-evenly",
  },
};
